### ISSUE TITLE
Create datalab for multiple different users / create a service account dynamically

### ISSUE THREAD

**Issue by adarobin** [terraform-google-modules/terraform-google-datalab#10]
The use case I have is that we have a data set in BigQuery that we would like researchers to be able to access from Datalab, but not be able to directly access the data themselves.

We implemented this by creating a distinct compute engine service account tied to a specific user and only giving BigQuery permissions to the service account.  We currently are using a bunch of hacks with a null_resource that don't always work correctly.  I'd love to be able to leverage this instead.

Since I can't use for_each for a module, these features would be necessary to get rid of our current  solution.

I'm happy to submit a PR if you would consider it.

**Comment by morgante** [comment]
Could you share more about what the interface for this might look like? Would definitely be happy to consider a PR.

**Comment by adarobin** [comment]
I was thinking about just overloading `datalab_user_email` to take a set of e-mail addresses instead of a single e-mail address.

You'd call something like this:
```hcl
module "datalab_instances" {
  source = "/Users/adarobin/Code/terraform-google-datalab//modules/default_instance"
  create_service_account = true
  datalab_user_email = ["user1@example.com", "user2@example.com"]
  project_id = var.project_id
  network_name = var.network_name
  subnet_name = var.subnet_name
  zone = "us-central1-a"
}
```
