### ISSUE TITLE
Merge default and gpu instance modules

### ISSUE THREAD

**Issue by nick4fake** [terraform-google-modules/terraform-google-datalab#12]
default_instance and gpu_instance modules look very similar.

I suggest merging them into one, leaving these as entrypoints populating required inputs.

cc @aaron-lane, @morgante

**Comment by taylorludwig** [comment]
I'll take a look at merging these and making them backwards compatible as possible.

**Comment by morgante** [comment]
Thanks, we might end up wanting to have a common module they both reference.
