### ISSUE TITLE
Using custom datalab image from a private registry.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-datalab#17]
Is there a way to provide docker login credentials in a secure way when the docker imaged for datalab is pulled from a private registry.  As far as I understand, it can only exist in GCR right now and pulled using the service account IAM permissions of the datalab instance.

Another relevant question:  can the image be changed once the datalab is created - will applying the change cause the datalab instance to restart or should restart be triggered manually for the image change to take effect?

**Comment by mikhail-khodorovskiy** [comment]
In the startup script below
```
download_docker_image() {
  # Since /root/.docker is not writable on the default image,
  # we need to set HOME to be a writable directory. This same
  # directory is used later on by the datalab.service.
  export OLD_HOME=$HOME
  export HOME=/home/datalab
  echo "Getting Docker credentials"
  docker-credential-gcr configure-docker
  echo "Pulling latest image: docker-registry.janusplatform.io/hsq-analytics-datalab/hsq-analytics-datalab:master"
  docker pull docker-registry.janusplatform.io/hsq-analytics-datalab/hsq-analytics-datalab:master
  export HOME=$OLD_HOME
}
```
logging into GCR, has to have an option to login to another docker registry with the credentials provided via https://cloud.google.com/secret-manager/docs/quickstart-secret-manager-api assuming the service account for the datalab has access to those credentials and secret names are provided as part of the module parameter.

**Comment by mikhail-khodorovskiy** [comment]
Created a PR to support the feature:  https://github.com/terraform-google-modules/terraform-google-datalab/pull/23

**Comment by g-awmalik** [comment]
Closing since this is stale and the comments on PR haven't been addressed in 2 years. Please reopen if necessary.
