### ISSUE TITLE
Allow for additional custom startup script.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-datalab#3]
We need the ability to deploy a security agent for monitoring the datalab VMs.  Can there be a way to specify a custom https://github.com/terraform-google-modules/terraform-google-datalab/blob/master/modules/template_files/templates/startup_script.tpl or an additional scrip when the instance is created?

**Comment by morgante** [comment]
Would you prefer a totally custom script or simply appending an additional custom startup script?

**Comment by mikhail-khodorovskiy** [comment]
Appending would probably be better - that way we can always pick up the changes you make to the default status script.

**Comment by morgante** [comment]
Ok, we should add a variable which allows for appending a custom script.
