### ISSUE TITLE
Don't create IAP google_compute_firewall_rule

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-datalab#4]
when I try to use the module multiple times for the same network, the iap firewall rule is created for every instances.  I  handle the rule on the project/network creation so I don't need the rule to be created every time the datalab instance is added.  Can the rule be made optional through a module variable?

**Comment by morgante** [comment]
Yes, we could add a variable to the `default_instance` module which disables the firewall module: https://github.com/terraform-google-modules/terraform-google-datalab/blob/master/modules/default_instance/main.tf#L24

**Comment by mikhail-khodorovskiy** [comment]
Yes, please.   Is there an ETA on that or should I fork the module in the meantime?

**Comment by morgante** [comment]
No ETA, feel free to fork and open a PR!
