### ISSUE TITLE
Allow for custom labels on the datalab instances.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-datalab#7]
Similar to https://www.terraform.io/docs/providers/google/r/compute_instance.html#labels allow passing labels that can be additevly added to the default labels.

**Comment by morgante** [comment]
This would need to be added as a labels variable on the two instance modules, then combine with the existing labels [here](https://github.com/terraform-google-modules/terraform-google-datalab/blob/master/modules/default_instance/main.tf#L62) and [here](https://github.com/terraform-google-modules/terraform-google-datalab/blob/master/modules/gpu_instance/main.tf#L63).
