### ISSUE TITLE
Enable secure boot if possible.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [terraform-google-modules/terraform-google-datalab#9]
The secure boot is disabled for the shielded VM datalab instance is running on.  The documentation https://cloud.google.com/security/shielded-cloud/shielded-vm seems like there is not really a reson for not having the instance have enable_secure_bot as true.  I have tested launching a default datalab instance with my fork of the module, and it seems to work just fine, at least with the default datalab image.

```
  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot          = false
    enable_vtpm                 = true
  }
```
https://github.com/terraform-google-modules/terraform-google-datalab/blob/master/modules/default_instance/main.tf#L99

Can you please make the secure boot true, explain when and why it can't be set to true in which case maybe make it configurable via module variables.

**Comment by morgante** [comment]
Sounds like a good idea, happy to look at a PR implementing this!

**Comment by mikhail-khodorovskiy** [comment]
It's obviously a trivial change - the question was more along the lines if anything would break if datlab would run with this flag being set to true.
